### ISSUE TITLE
Logic Error in get_coords() call

### ISSUE THREAD

**Issue by ngjunsiang** [JordanLow/ChessGame#25]
https://github.com/JordanLow/ChessGame/blob/b6676c4674417c4ddc2992fa72eee6eab9a8537f/chess.py#L245

## Console log

```
Traceback (most recent call last):
  File "/home/runner/ChessGame/test_chess.py", line 192, in test_no_jump
    self.assertFalse(game.valid_move((4, 4), (4, 0)))
  File "/home/runner/ChessGame/chess.py", line 226, in valid_move
    if self.check_spaces_btw(start, end):
  File "/home/runner/ChessGame/chess.py", line 245, in check_spaces_btw
    if self.get_coords((start[0],i)) != None:
TypeError: get_coords() missing 1 required positional argument: 'colour'
```

**Comment by JordanLow** [comment]
Subset of #24
