### ISSUE TITLE
Unable to promote pieces

### ISSUE THREAD

**Issue by ngjunsiang** [JordanLow/ChessGame#7]
chess.py [line 63](https://github.com/JordanLow/ChessGame/blob/c9b8701a34a6ce8b15a8eab14493fa16fc61665b/chess.py#L63), [line 66](https://github.com/JordanLow/ChessGame/blob/c9b8701a34a6ce8b15a8eab14493fa16fc61665b/chess.py#L66)
`self.add(end,Queen(black))`
`self.add(end,Queen(white))`

## Actual output

```
Traceback (most recent call last):
  File "/home/runner/ChessGame/test_chess.py", line 110, in test_pawn_promotion
    game.update((i, 6), (i, 7))
  File "/home/runner/ChessGame/chess.py", line 210, in update
    self.move(start, end)
  File "/home/runner/ChessGame/chess.py", line 66, in move
    self.add(end,Queen(white))
NameError: name 'white' is not defined
```

## Fix

Input for `Queen` instantiation should be a string

**Comment by JordanLow** [comment]
Fixed
